// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcPoznamky.Data;

namespace MvcPoznamky.Migrations
{
    [DbContext(typeof(MvcPoznamkyContext))]
    [Migration("20210413151130_ProcToNefunguje")]
    partial class ProcToNefunguje
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcPoznamky.Models.Poznamka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumVytvoreni")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UzivatelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UzivatelId");

                    b.ToTable("Poznamky");
                });

            modelBuilder.Entity("MvcPoznamky.Models.Uzivatel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Heslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Jmeno")
                        .IsUnique();

                    b.ToTable("Uzivatele");
                });

            modelBuilder.Entity("MvcPoznamky.Models.Poznamka", b =>
                {
                    b.HasOne("MvcPoznamky.Models.Uzivatel", "Uzivatel")
                        .WithMany("Poznamky")
                        .HasForeignKey("UzivatelId");

                    b.Navigation("Uzivatel");
                });

            modelBuilder.Entity("MvcPoznamky.Models.Uzivatel", b =>
                {
                    b.Navigation("Poznamky");
                });
#pragma warning restore 612, 618
        }
    }
}
